name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install pymysql pyjwt -t package
        working-directory: tech-challange-lambda

      - name: Package Lambda Function
        run: |
          cp lambda.py package/
          cd package
          zip -r ../function.zip .
          cd ..
        working-directory: tech-challange-lambda

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_DB_HOST: ${{ secrets.DB_HOST }}
          TF_VAR_DB_USER: ${{ secrets.DB_USER }}
          TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TF_VAR_SECRET: ${{ secrets.SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}